import Cards from './Cards.js';

import {
    forethought,
    midas_touch,
    metalwork,
    healing_salve,
    stamina,
    enigma_form,
    robustness,
    masterwork,
    violent_rage,
    repurpose,
    shield_form,
    flywheel,
    vengeance,
    short_temper,
    explosivity,
    cardistry,
    haste,
    patience,
    uniformity,
    high_voltage,
    strange_tail,
    rebuke,
    non_newtonian,
    supernatural,
    layers,
    emergence,
    screen,
    cycle_barrier,
    bastion,
    bodiless_form,
    overpowered,
    guzzle,
    prescience,
    acuity,
    magic_bonus,
    magic_multiplier,
    prisma,
    storm,
    renewal,
    dark_codex,
    bolster,
    radioactive,
    depthsight,
    blacksmith,
    dark_knowledge,
    sage,
    reckless_abandon,
    stance_dance,
    euphoria,
    strength_beyond_measure,
    colossus,
    spectrum,
  } from './ability_cards/index.js';

import {
    parry,
    stomp,
    quick_buck,
    hind_kick,
    quick_stab,
    hammer_thrust,
    clever_trick,
    pierce,
    tail_whip,
    burning_strike,
    wing_beat,
    unstable_attack,
    hinder_strike,
    blitz,
    concuss,
    ambush,
    wing_sweep,
    timed_attack,
    cheap_shot,
    stampede,
    spin_kick,
    exposed_strike,
    familiar_strike,
    frenzied_charge,
    rainbow_thrust,
    chaos_thrust,
    elemental_thrust,
    dark_thrust,
    arsenal,
    smash_and_grab,
    fury,
    premeditated_slash,
    collateral_damage,
    surprise_attack,
    auto_attack,
    sudden_barrage,
    provisioned_attack,
    thwack,
    devastator,
    weaponry,
    amass,
    berserk,
    clever_barrage,
    freeze,
    scorch,
    ultra_kill,
    auxiliary_kill,
    mega_kill,
    disintegrate,
    obliterate,
    death_blow,
    overwhelming_barrage,
    critical_hit,
    erupt,
    monster_kill,
    malevolent_blow,
  } from './attack_cards/index.js';

import {
    rainbow_charge,
    chaos_charge,
    dark_charge,
    elemental_charge,
    risky_charge,
    aligned_charge,
    delayed_charge,
    sacrificial_charge,
    risky_charm,
    rainbow_charm,
    chaos_charm,
    dark_charm,
    elemental_charm,
    beautiful_spell,
    delightful_spell,
    wonderful_spell,
    sparkling_rainbow_spell,
    shimmering_rainbow_spell,
    luminous_rainbow_spell,
    flash_of_magic,
    aligned_charm,
    grow,
    focus,
    mystical_protection,
    metamorphose,
    cryptic_rune,
    magical_maneuver,
    recaster,
    bloom,
    fire_spell,
    ice_spell,
    delayed_spell,
    sacrificial_spell,
    magic_flare,
    risky_incantation,
    maelstrom,
    master_summoner,
    master_sorcerer,
    master_conjurer,
    secret_arts,
    dazzle,
    razzle,
    master_of_all,
    mystical_energy,
    mystical_maneuver,
    vortex,
    ancient_runestone,
    fleeting_incantation,
    obelisk,
    annihilation,
    flare_up,
    legion,
    ignite,
    perfect_storm,
    eternal_runestone,
  } from './magic_cards/index.js';

  import {
    jab,
    shield,
    leather_armor,
    stun,
    rainbow_orb,
    aura_stance,
    sparkle_stance,
    shimmer_stance,
    shimmer,
    sparkle,
    aura,
    courage,
    familiar_agony,
    slash,
    fleeting_slash,
    lingering_slash,
    momentous_slash,
    safety,
    energize,
    boost,
    auxiliary,
    impresa,
    ouroboros,
    tesseract,
    battle_move,
    battle_combo,
    battle_sequence,
    battle_finisher,
    self_enhance,
    self_advance,
    self_fulfill,
    rainbow_converter,
    chaos_converter,
    dark_converter,
    elemental_converter,
    sparks,
    bottled_speed,
    bottled_energy,
    bottled_armor,
    bottled_block,
    bottled_attack,
    bottled_cards,
    bottled_magic,
    release,
    acquire,
    dismantle,
    atomic,
    nuclear,
    head_shot,
    thrash,
    forestall,
    evade,
    blaze_of_magic,
    magic_burst,
    spewnicorn_spray,
    junk,
    debris,
    chaff,
    gunk,
    execrate,
    flay,
    curse,
    timid,
    lethargy,
    briars,
    broken,
    mired,
  } from './non-addable_cards/index.js';

  import {
    divert,
    recoil,
    repel,
    thwart,
    deter,
    chain_mail_armor,
    cleanse,
    remember,
    glowing_orb,
    fractured_orb,
    plate_armor,
    fleeting_shelter,
    fleeting_shield,
    nullify,
    neigh,
    whinny,
    death_stare,
    fortify,
    hardened_feathers,
    attuned_barrier,
    charged_barrier,
    fissile,
    sidestep,
    fortress,
    safeguard,
    gallop,
    sprint,
    gift,
    sacrifice,
    purge,
    scavenge,
    gears_of_war,
    beautiful,
    delightful,
    wonderful,
    bravery,
    clever_maneuver,
    riffle,
    collect,
    entity,
    unstable_field,
    disavow,
    ruin,
    make_ready,
    cutting_ring,
    distracting_ring,
    jester,
    strange_mushroom,
    target,
    frost_armor,
    flame_armor,
    garrison,
    elude,
    bulwark,
    steel_hide,
    reactor,
    power_surge,
    enrich,
    trade_up,
    tactics,
    unearth,
    blockade,
    mezmerize,
    elite_maneuver,
    expunge,
    mysterious_fissure,
    thresh,
    charge,
    surge,
    roar,
    superstorm,
    cloudburst,
    purify,
    forbid,
    weaponsmith,
    scholar,
    paralyzing_touch,
    blitzkrieg,
    cascade,
    blank_slate,
    seeing_ring,
    crippling_stare,
    citadel,
    everarmor,
    adrenaline_rush,
    untold_contract,
    myriad,
  } from './tool_cards/index.js';

import {
    rusty_dagger,
    polished_dagger,
    piercer,
    shredder,
    stormknife,
    shiv_of_the_abyss,
    wooden_sword,
    broadsword,
    hardened_steel,
    champions_cutlass,
    glacial_blade,
    nightfury,
    loggers_axe,
    battle_axe,
    throwing_axe,
    swift_battle_axe,
    sharpened_axe,
    cleave,
    redfury,
    forge,
    dragons_bane,
    endless_edge,
    deathmaker,
    old_hammer,
    reinforced_hammer,
    tungsten_hammer,
    molten_hammer,
    hammer_of_justice,
    gravitas,
    firmament_mover,
    singing_mallet,
    blunt_pike,
    serrated_pike,
    ancient_spear,
    runed_bayonet,
    cursed_spike,
    frozen_harpoon,
    ornate_javelin,
    double_headed_lance,
    farmers_scythe,
    crescentblade,
    sharpened_scythe,
    blackblade,
    spiked_scythe,
    greenshears,
    glowscythe,
    bonesaw,
    treecleaver,
    mantleblight,
    armyfeller,
    reaper,
    fleeting_deathblade,
    hickory_wand,
    walnut_wand,
    black_oak_wand,
    hooked_wand,
    glowing_wand,
    glowing_sceptre,
    darkfeather,
    heart_of_chaos,
    evernature,
    arcana_prismatica,
    crooked_staff,
    twisted_staff,
    slotted_staff,
    carved_staff,
    gold_staff,
    green_staff,
    purple_staff,
    sapphire_staff,
    emerald_staff,
    ruby_staff,
    emanating_staff,
    shuddering_staff,
    quaking_staff,
    runemark,
    darksphere,
    staff_of_wonder,
    skycaller,
    windrift,
    ember,
    deepcore,
    felcrystal,
    burning_branch,
    flaming_torch,
    blazing_torch,
    strangefire,
    lumenfire,
    endless_light,
    dreadfurnace,
  } from './weapons/index.js';

const ALL_CARDS = [

    /* NON-ADDABLE CARDS */
    /* Starting Cards: */
    new Cards(jab),
    new Cards(shield),
    new Cards(leather_armor),
    new Cards(stun),
    new Cards(rainbow_orb),



    /* Cards Added By Other Cards/Events: */
    new Cards(aura_stance),
    new Cards(sparkle_stance),
    new Cards(shimmer_stance),
    new Cards(shimmer),
    new Cards(sparkle),
    new Cards(aura),
    new Cards(courage),
    new Cards(familiar_agony),
    new Cards(slash),
    new Cards(fleeting_slash),
    new Cards(lingering_slash),
    new Cards(momentous_slash),
    new Cards(safety),
    new Cards(energize),
    new Cards(boost),
    new Cards(auxiliary),
    new Cards(impresa),
    new Cards(ouroboros),
    new Cards(tesseract),
    new Cards(battle_move),
    new Cards(battle_combo),
    new Cards(battle_sequence),
    new Cards(battle_finisher),
    new Cards(self_enhance),
    new Cards(self_advance),
    new Cards(self_fulfill),
    new Cards(rainbow_converter),
    new Cards(chaos_converter),
    new Cards(dark_converter),
    new Cards(elemental_converter),
    new Cards(sparks),
    new Cards(bottled_speed),
    new Cards(bottled_energy),
    new Cards(bottled_armor),
    new Cards(bottled_block),
    new Cards(bottled_attack),
    new Cards(bottled_cards),
    new Cards(bottled_magic),
    new Cards(release),
    new Cards(acquire),
    new Cards(dismantle),
    new Cards(atomic),
    new Cards(nuclear),
    new Cards(head_shot),
    new Cards(thrash),
    new Cards(forestall),
    new Cards(evade),
    new Cards(blaze_of_magic),
    new Cards(magic_burst),
    new Cards(spewnicorn_spray),


    /* Clutter: */
    new Cards(junk),
    new Cards(debris),
    new Cards(chaff),
    new Cards(gunk),
    new Cards(execrate),
    new Cards(flay),
    new Cards(curse),
    new Cards(timid),
    new Cards(lethargy),
    new Cards(briars),
    new Cards(broken),
    new Cards(mired),





    /* WEAPONS */
    new Cards(rusty_dagger),
    new Cards(polished_dagger),
    new Cards(piercer),
    new Cards(shredder),
    new Cards(stormknife),
    new Cards(shiv_of_the_abyss),
    new Cards(wooden_sword),
    new Cards(broadsword),
    new Cards(hardened_steel),
    new Cards(champions_cutlass),
    new Cards(glacial_blade),
    new Cards(nightfury),
    new Cards(loggers_axe),
    new Cards(battle_axe),
    new Cards(throwing_axe),
    new Cards(swift_battle_axe),
    new Cards(sharpened_axe),
    new Cards(cleave),
    new Cards(redfury),
    new Cards(forge),
    new Cards(dragons_bane),
    new Cards(endless_edge),
    new Cards(deathmaker),
    new Cards(old_hammer),
    new Cards(reinforced_hammer),
    new Cards(tungsten_hammer),
    new Cards(molten_hammer),
    new Cards(hammer_of_justice),
    new Cards(gravitas),
    new Cards(firmament_mover),
    new Cards(singing_mallet),
    new Cards(blunt_pike),
    new Cards(serrated_pike),
    new Cards(ancient_spear),
    new Cards(runed_bayonet),
    new Cards(cursed_spike),
    new Cards(frozen_harpoon),
    new Cards(ornate_javelin),
    new Cards(double_headed_lance),
    new Cards(farmers_scythe),
    new Cards(crescentblade),
    new Cards(sharpened_scythe),
    new Cards(blackblade),
    new Cards(spiked_scythe),
    new Cards(greenshears),
    new Cards(glowscythe),
    new Cards(bonesaw),
    new Cards(treecleaver),
    new Cards(mantleblight),
    new Cards(armyfeller),
    new Cards(reaper),
    new Cards(fleeting_deathblade),
    new Cards(hickory_wand),
    new Cards(walnut_wand),
    new Cards(black_oak_wand),
    new Cards(hooked_wand),
    new Cards(glowing_wand),
    new Cards(glowing_sceptre),
    new Cards(darkfeather),
    new Cards(heart_of_chaos),
    new Cards(evernature),
    new Cards(arcana_prismatica),
    new Cards(crooked_staff),
    new Cards(twisted_staff),
    new Cards(slotted_staff),
    new Cards(carved_staff),
    new Cards(gold_staff),
    new Cards(green_staff),
    new Cards(purple_staff),
    new Cards(sapphire_staff),
    new Cards(emerald_staff),
    new Cards(ruby_staff),
    new Cards(emanating_staff),
    new Cards(shuddering_staff),
    new Cards(quaking_staff),
    new Cards(runemark),
    new Cards(darksphere),
    new Cards(staff_of_wonder),
    new Cards(skycaller),
    new Cards(windrift),
    new Cards(ember),
    new Cards(deepcore),
    new Cards(felcrystal),
    new Cards(burning_branch),
    new Cards(flaming_torch),
    new Cards(blazing_torch),
    new Cards(strangefire),
    new Cards(lumenfire),
    new Cards(endless_light),
    new Cards(dreadfurnace),







    /* ATTACK CARDS */
    /* Common: */
    new Cards(parry),
    new Cards(stomp),
    new Cards(quick_buck),
    new Cards(hind_kick),
    new Cards(quick_stab),
    new Cards(hammer_thrust),
    new Cards(clever_trick),
    new Cards(pierce),
    new Cards(tail_whip),
    new Cards(burning_strike),
    new Cards(wing_beat),
    new Cards(unstable_attack),
    new Cards(hinder_strike),
    new Cards(blitz),
    new Cards(concuss),
    new Cards(ambush),
    new Cards(wing_sweep),
    new Cards(timed_attack),
    new Cards(cheap_shot),




    /* Uncommon: */
    new Cards(stampede),
    new Cards(spin_kick),
    new Cards(exposed_strike),
    new Cards(familiar_strike),
    new Cards(frenzied_charge),
    new Cards(rainbow_thrust),
    new Cards(chaos_thrust),
    new Cards(elemental_thrust),
    new Cards(dark_thrust),
    new Cards(arsenal),
    new Cards(smash_and_grab),
    new Cards(fury),
    new Cards(premeditated_slash),
    new Cards(collateral_damage),
    new Cards(surprise_attack),
    new Cards(auto_attack),
    new Cards(sudden_barrage),
    new Cards(provisioned_attack),
    new Cards(thwack),



    /* Rare: */
    new Cards(devastator),
    new Cards(weaponry),
    new Cards(amass),
    new Cards(berserk),
    new Cards(clever_barrage),
    new Cards(freeze),
    new Cards(scorch),
    new Cards(ultra_kill),
    new Cards(auxiliary_kill),
    new Cards(mega_kill),
    new Cards(disintegrate),
    new Cards(obliterate),


    /* Legendary: */
    new Cards(death_blow),
    new Cards(overwhelming_barrage),
    new Cards(critical_hit),
    new Cards(erupt),
    new Cards(monster_kill),
    new Cards(malevolent_blow),







    /* TOOL CARDS */
    /* Common: */
    new Cards(divert),
    new Cards(recoil),
    new Cards(repel),
    new Cards(thwart),
    new Cards(deter),
    new Cards(chain_mail_armor),
    new Cards(cleanse),
    new Cards(remember),
    new Cards(glowing_orb),
    new Cards(fractured_orb),
    new Cards(plate_armor),
    new Cards(fleeting_shelter),
    new Cards(fleeting_shield),
    new Cards(nullify),
    new Cards(neigh),
    new Cards(whinny),
    new Cards(death_stare),
    new Cards(fortify),
    new Cards(hardened_feathers),
    new Cards(attuned_barrier),
    new Cards(charged_barrier),
    new Cards(fissile),
    new Cards(sidestep),




    /* Uncommon: */
    new Cards(fortress),
    new Cards(safeguard),
    new Cards(gallop),
    new Cards(sprint),
    new Cards(gift),
    new Cards(sacrifice),
    new Cards(purge),
    new Cards(scavenge),
    new Cards(gears_of_war),
    new Cards(beautiful),
    new Cards(delightful),
    new Cards(wonderful),
    new Cards(bravery),
    new Cards(clever_maneuver),
    new Cards(riffle),
    new Cards(collect),
    new Cards(entity),
    new Cards(unstable_field),
    new Cards(disavow),
    new Cards(ruin),
    new Cards(make_ready),
    new Cards(cutting_ring),
    new Cards(distracting_ring),
    new Cards(jester),
    new Cards(strange_mushroom),
    new Cards(target),
    new Cards(frost_armor),
    new Cards(flame_armor),
    new Cards(garrison),
    new Cards(elude),



    /* Rare: */
    new Cards(bulwark),
    new Cards(steel_hide),
    new Cards(reactor),
    new Cards(power_surge),
    new Cards(enrich),
    new Cards(trade_up),
    new Cards(tactics),
    new Cards(unearth),
    new Cards(blockade),
    new Cards(mezmerize),
    new Cards(elite_maneuver),
    new Cards(expunge),
    new Cards(mysterious_fissure),
    new Cards(thresh),
    new Cards(charge),
    new Cards(surge),
    new Cards(roar),
    new Cards(superstorm),
    new Cards(cloudburst),
    new Cards(purify),
    new Cards(forbid),
    new Cards(weaponsmith),
    new Cards(scholar),
    new Cards(paralyzing_touch),
    new Cards(blitzkrieg),
    new Cards(cascade),
    new Cards(blank_slate),
    new Cards(seeing_ring),



    /* Legendary */
    new Cards(crippling_stare),
    new Cards(citadel),
    new Cards(everarmor),
    new Cards(adrenaline_rush),
    new Cards(untold_contract),
    new Cards(myriad),



    /* ABILITY CARDS */
    /* common */



    /* uncommon */
    new Cards(forethought),
    new Cards(midas_touch),
    new Cards(metalwork),
    new Cards(healing_salve),
    new Cards(stamina),
    new Cards(enigma_form),
    new Cards(robustness),
    new Cards(masterwork),
    new Cards(violent_rage),
    new Cards(repurpose),
    new Cards(shield_form),
    new Cards(flywheel),
    new Cards(vengeance),
    new Cards(short_temper),
    new Cards(explosivity),

    new Cards(cardistry),
    new Cards(haste),
    new Cards(patience),
    new Cards(uniformity),
    new Cards(high_voltage),
    new Cards(strange_tail),
    new Cards(rebuke),
    new Cards(non_newtonian),
    new Cards(supernatural),
    new Cards(layers),
    new Cards(emergence),
    new Cards(screen),
    new Cards(cycle_barrier),





    /* rare */
    new Cards(bastion),
    new Cards(bodiless_form),
    new Cards(overpowered),
    new Cards(guzzle),
    new Cards(prescience),
    new Cards(acuity),
    new Cards(magic_bonus),
    new Cards(magic_multiplier),
    new Cards(prisma),
    new Cards(storm),
    new Cards(renewal),
    new Cards(dark_codex),
    new Cards(bolster),
    new Cards(radioactive),
    new Cards(depthsight),
    new Cards(blacksmith),
    new Cards(dark_knowledge),
    new Cards(sage),
    new Cards(reckless_abandon),
    new Cards(stance_dance),

    /* legendary */
    new Cards(euphoria),
    new Cards(strength_beyond_measure),
    new Cards(colossus),
    new Cards(spectrum),








    /* MAGIC CARDS */
    /* common */

    new Cards(rainbow_charge),
    new Cards(chaos_charge),
    new Cards(dark_charge),
    new Cards(elemental_charge),
    new Cards(risky_charge),
    new Cards(aligned_charge),
    new Cards(delayed_charge),
    new Cards(sacrificial_charge),
    new Cards(risky_charm),
    new Cards(rainbow_charm),
    new Cards(chaos_charm),
    new Cards(dark_charm),
    new Cards(elemental_charm),
    new Cards(beautiful_spell),
    new Cards(delightful_spell),
    new Cards(wonderful_spell),
    new Cards(sparkling_rainbow_spell),
    new Cards(shimmering_rainbow_spell),
    new Cards(luminous_rainbow_spell),
    new Cards(flash_of_magic),



    /* uncommon */
    new Cards(aligned_charm),
    new Cards(grow),
    new Cards(focus),
    new Cards(mystical_protection),
    new Cards(metamorphose),
    new Cards(cryptic_rune),
    new Cards(magical_maneuver),
    new Cards(recaster),
    new Cards(bloom),
    new Cards(fire_spell),
    new Cards(ice_spell),
    new Cards(delayed_spell),
    new Cards(sacrificial_spell),
    new Cards(magic_flare),




    /* rare */

    new Cards(risky_incantation),
    new Cards(maelstrom),
    new Cards(master_summoner),
    new Cards(master_sorcerer),
    new Cards(master_conjurer),
    new Cards(secret_arts),
    new Cards(dazzle),
    new Cards(razzle),
    new Cards(master_of_all),
    new Cards(mystical_energy),
    new Cards(mystical_maneuver),
    new Cards(vortex),
    new Cards(ancient_runestone),
    new Cards(fleeting_incantation),
    new Cards(obelisk),

    /* legendary */
    new Cards(annihilation),
    new Cards(flare_up),
    new Cards(legion),
    new Cards(ignite),
    new Cards(perfect_storm),
    new Cards(eternal_runestone),



];

export { ALL_CARDS };