export default {
  id: "blazing_torch",
  name: "Blazing Torch",
  type: "magic",
  mana: 3,
  weight: 0.5,
  use: 2,
  weapon: true,
  addable: false,
  tier: "uncommon",
  magic: [{ type: "aligned", amount: 10 }],
  effects: [{ effect: "mage", amount: 1, turns: -1 }],
  sound: "magic4",
  additionalDesc: "Level III Weapon",
  slots: 1,
  shardUpgrades: {
    magic: [{ type: "aligned", amount: 15 }],
  },
  trade: ["strangefire"],
};
