export default {
  id: "darksphere",
  name: "Darksphere",
  type: "magic",
  mana: 0,
  weight: 0.6,
  use: 3,
  weapon: true,
  addable: false,
  tier: "rare",
  magic: [{ type: "aligned", amount: 9 }],
  effects: [{ effect: "thunder", amount: 0.1, turns: -1 }],
  sound: "magic4",
  additionalDesc: "Level VI Weapon",
  slots: 1,
  shardUpgrades: {
    use: 4,
    magic: [{ type: "aligned", amount: 15 }],
  },
};
