export default {
  id: "spewnicorn_spray",
  name: "Spewnicorn Spray",
  type: "tool",
  mana: 0,
  breakable: true,
  use: 3,
  tier: "legendary",
  addable: false,
  descOverride: "Deus Ex Machina. Gain all power-ups possible.",
  blk: [50],
  effects: [
    { effect: "speed", amount: 2, turns: -1 },
    { effect: "solid", amount: 5, turns: -1 },
    { effect: "might", amount: 5, turns: -1 },
    { effect: "punch", amount: 1, turns: -1 },
    { effect: "mend", amount: 5, turns: -1 },
    { effect: "craft", amount: 2, turns: -1 },
    { effect: "cunning", amount: 5, turns: 2 },
    { effect: "vigor", amount: 5, turns: 2 },
    { effect: "stout", amount: 5, turns: 2 },
    { effect: "muster", amount: 5, turns: 2 },
    { effect: "rowdy", amount: 50, turns: 2 },
    { effect: "fierce", amount: 50, turns: 2 },
    { effect: "mastery", amount: 0.5, turns: 2 },
    { effect: "heal", amount: 5, turns: 2 },
    { effect: "conjure", amount: 5, turns: 2 },
    { effect: "sorcery", amount: 5, turns: 2 },
    { effect: "momentum", amount: 5, turns: 2 },
    { effect: "wield", amount: 5, turns: 2 },
    { effect: "resistance", amount: 5, turns: 2 },
    { effect: "lemonade", amount: 5, turns: 2 },
    { effect: "spikes", amount: 5, turns: 2 },
    { effect: "vex", amount: 5, turns: 2 },
    { effect: "mage", amount: 5, turns: 2 },
    { effect: "enchanter", amount: 5, turns: 2 },
    { effect: "summon", amount: 10, turns: 2 },
    { effect: "arcane", amount: 5, turns: 2 },
    { effect: "fatality", amount: 1.5, turns: 1, persist: true },
    { effect: "retaliate", amount: 5, turns: 2 },
    { effect: "mystery", amount: 2, turns: -1 },
    { effect: "regen", amount: 5, turns: 2 },
    { effect: "wisdom", amount: 2, turns: 2 },
    { effect: "lightning", amount: 5, turns: -1 },
    { effect: "thunder", amount: 2, turns: 2 },
    { effect: "retain", amount: 2, turns: 2 },
    { effect: "insulate", amount: 1, turns: -1 },
    { effect: "irradiate", amount: 5, turns: -1 },
    { effect: "replenish", amount: 1, turns: -1 },
    { effect: "combiner", amount: 1, turns: -1 },
    { effect: "angered", amount: 4, turns: 2 },
    { effect: "hardened", amount: 8, turns: 2 },
    { effect: "shapeshifter", amount: 25, turns: 2 },
    { effect: "fend", amount: 18, turns: 2 },
    { effect: "ward", amount: 18, turns: 2 },
    { effect: "cover", amount: 18, turns: 2 },
    { effect: "preserve", amount: 18, turns: 2 },
  ],
  abilities: [
    { ability: "protection", turns: 2, enabled: true },
    { ability: "unreachable", turns: 2, enabled: true },
    { ability: "tank", turns: 2, enabled: true },
    { ability: "toothache", turns: 2, enabled: true },
    { ability: "prepared", turns: 2, enabled: true },
    { ability: "bless", turns: -1, enabled: true },
    { ability: "hypnotize", turns: 2, enabled: true },
    { ability: "stockpile", turns: 2, enabled: true },
    { ability: "sift", turns: -1, enabled: true },
    { ability: "panic", turns: 2, enabled: true },
    { ability: "expirex", turns: -1, enabled: true },
    { ability: "magick", turns: -1, enabled: true },
    { ability: "expirex", turns: -1, enabled: true },
    { ability: "amplify", turns: -1, enabled: true },
    { ability: "explode", turns: 2, enabled: true },
    { ability: "supernatural", turns: -1, enabled: true },
  ],
  magic: [{ type: "aligned", amount: 5 }],
};
